datasets:
  Function:
    random_seed: 0
    n_samples: 200
    n_train_ratio: 0.8
    fn_kwargs:
      fn: 'lambda x:np.sin(x)'
      bounds: [[-10,10]]
    noise_kwargs:
      mean: 0
      variance: 0.0001
algorithms:

  # GPflowGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   kernel: RBF
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # SklearnGP:
  #   test_mode: True
  #   random_seed: 0
  #   m_repeats: 1
  #   kernel: RBF
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  GPyGP:
    random_seed: 0
    m_repeats: 1
    kernel: RBF
    kernel_kwargs:
      lengthscale: 1.0
      scale_variance: population
      noise_variance: 0.09

  # GeorgeGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   solver: HODLRSolver
  #   kernel: ExpSquaredKernel
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # GeorgeGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   solver: BasicSolver
  #   kernel: ExpSquaredKernel
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchAlexanderGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   kernel: RBFKernel
  #   output_device: cuda:0
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchAlexanderGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   kernel: RBFKernel
  #   output_device: cpu
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09


  # PyTorchGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   kernel: RBFKernel
  #   output_device: cuda:0
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchGP:
  #   random_seed: 0
  #   m_repeats: 1
  #   kernel: RBFKernel
  #   output_device: cpu
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09
