datasets:
  Function:
    random_seed: 0
    n_samples: 200
    fn_kwargs:
      fn: 'lambda x:np.sin(x)'
      bounds: [[-10,10]]
    noise_kwargs:
      mean: 0
      variance: 0.0001
algorithms:
  # SklearnGP:
  #   random_seed: 0
  #   kernel: RBF
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # GPyGP:
  #   random_seed: 0
  #   kernel: RBF
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  GeorgeGP:
    random_seed: 0
    solver: HODLRSolver
    kernel: ExpSquaredKernel
    kernel_kwargs:
      lengthscale: 1.0
      scale_variance: population
      noise_variance: 0.09

  # GeorgeGP:
  #   random_seed: 0
  #   solver: BasicSolver
  #   kernel: ExpSquaredKernel
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchAlexanderGP:
  #   random_seed: 0
  #   solver: HODLRSolver
  #   kernel: ExpSquaredKernel
  #   output_device: cuda:0
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchGP:
  #   random_seed: 0
  #   kernel: RBFKernel
  #   output_device: cuda:0
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchGP:
  #   random_seed: 0
  #   kernel: RBFKernel
  #   output_device: cpu
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchGP:
  #   random_seed: 0
  #   kernel: RBFKernel
  #   output_device: cuda:0
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09

  # PyTorchGP:
  #   random_seed: 0
  #   kernel: RBFKernel
  #   output_device: cpu
  #   n_devices: 1
  #   preconditioner_size: 100
  #   kernel_kwargs:
  #     lengthscale: 1.0
  #     scale_variance: population
  #     noise_variance: 0.09