datasets:
  Function:
    random_seed: 0
    n_samples: 200
    fn_kwargs:
      fn: 'lambda x:np.sin(x)'
      bounds: [[-10,10]]
    noise_kwargs:
      mean: 0
      variance: 0.0001
algorithms:
  GeorgeGP:
    random_seed: 0
    solver: HODLRSolver
    kernel: ExpSquaredKernel
    kernel_kwargs:
      lengthscale: 1.0
      variance: population
    noise_variance: 0.09